language: java
sudo: required
jdk: oraclejdk8
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
cache:
  directories:
    - '$HOME/.m2/repository'
script:
  - ./mvnw clean install -B
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`set -x; if [ "$TRAVIS_BRANCH" == "develop" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=sunilquadros69/forex
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME

