---
spring:
  profiles: cloud
  application:
   name: forex-service
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}
  client:
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.url}

